default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "attendance_dev" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "dev" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "devpass" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "attendance_test" } %>_test
  username: <%= ENV.fetch("DATABASE_USERNAME") { "dev" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "devpass" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "attendance_production" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
