services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: attendance_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: bash -c "bundle install && rails s -b 0.0.0.0"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://dev:devpass@db:5432/attendance_dev
    ports: 
      - "3000:3000"
    depends_on: 
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data: