source "https://rubygems.org"

# Rails本体
gem "rails", "~> 7.2.2"
# Active RecordでPostgreSQLを使う
gem "pg", "~> 1.1"
# Pumaウェブサーバー [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# JSON API用 [https://github.com/rails/jbuilder]
# gem "jbuilder"
# 本番でAction Cable用Redis
# gem "redis", ">= 4.0.1"

# Redisの高機能データ型 [https://github.com/rails/kredis]
# gem "kredis"

# パスワード認証用 [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows用タイムゾーンデータ
gem "tzinfo-data", platforms: %i[ windows jruby ]

# 起動高速化
gem "bootsnap", require: false

# 画像変換 [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# CORS対応
gem "rack-cors"

# 認証
gem "devise", "~> 4.9.4"

# 認可
gem "pundit", "~> 2.3"

# Excel出力
gem "rubyXL", "~> 3.4"

group :development, :test do
  # デバッグ用
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # セキュリティ脆弱性チェック [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # コードスタイルチェック (利用可能な最新版: 1.77)
  gem "rubocop", "~> 1.77", require: false

  # テスト(RSpec/FactoryBot)
  gem "rspec-rails", "~> 8.0"
  gem "factory_bot_rails", "~> 6.5"
end

group :development do
  # 環境変数管理
  gem "dotenv-rails", "~> 3.1"
end

